services:
  postgres:
    image: postgres:15
    container_name: distributed_task_queue_db
    env_file:
      - .env
    environment:
      - POSTGRES_INITDB_ARGS=--lc-messages=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports:
      - "64253:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: distributed_task_queue_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]


volumes:
  postgres_data:
  redis_data:
